// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
	DATABASE_URL: string;
	CREATE_TWEETS_QUEUE: Queue;
	CREATE_TWEETS_QUEUE_DLQ: Queue;
}
